import { createFileRoute } from '@tanstack/react-router';
import { Plane, Database, ChartNoAxesCombined, SlidersHorizontal, ClipboardCheck, FileChartColumn, Code2, Globe2, TrendingUp, BarChart3, Building2, Landmark, CircleCheck, UserRound, ShieldCheck, ScanSearch, Network, Layers3, AlertCircle, ArrowDown, Search, Route as RouteIcon, BookOpen, Activity, CircleHelp, CalendarDays } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Navbar, Footer, SectionHeader, InfoCard, SourceLink } from '@/components/airix-ui';
import { GlossaryTool, ExampleTool, ExplorerTool, BacktestingTool, IndexCalculator, JevonsCalculator } from '@/components/airix-tools';
import { sources } from '@/lib/airix-data';
import aircraft from '@/assets/airix-aircraft.jpg';

export const Route = createFileRoute('/')({
  head: () => ({ meta: [
    { title: 'AIRIX — Airfare Intelligence Hub' },
    { name: 'description', content: 'Explore the proposed Automated Indian Airfare Index: methodology, illustrative fare dashboards, learning tools and calculators.' },
    { property: 'og:title', content: 'AIRIX — Airfare Intelligence Hub' },
    { property: 'og:description', content: 'A proposed project concept for understanding domestic Indian airfare movements with illustrative data and interactive tools.' },
    { property: 'og:type', content: 'website' },
    { name: 'twitter:card', content: 'summary_large_image' },
  ] }), component: Index,
});
const pipeline = [
  { icon: Plane, title: 'Airline Websites & OTAs', note: 'Potential sources' },
  { icon: Database, title: 'Fare Collection', note: 'Permitted observations' },
  { icon: SlidersHorizontal, title: 'Data Normalization', note: 'Comparable fares' },
  { icon: ChartNoAxesCombined, title: 'Statistical Model', note: 'Price relatives' },
  { icon: Activity, title: 'AIRIX', note: 'Proposed index' },
];
const steps = [
  { icon: ScanSearch, title: 'Data Collection' }, { icon: SlidersHorizontal, title: 'Cleaning & Normalization' },
  { icon: ClipboardCheck, title: 'Validation' }, { icon: ChartNoAxesCombined, title: 'Index Calculation' },
  { icon: BarChart3, title: 'Dashboard' }, { icon: Code2, title: 'API' },
];
function Flow({ items }: { items: string[] }) { return <div className="flow-list">{items.map((item,i) => <div key={item}><div className="flow-node">{item}</div>{i < items.length-1 && <div className="flow-arrow" aria-hidden="true">↓</div>}</div>)}</div>; }
function Index() { return <>
  <Navbar />
  <main className="reference-layout">
    <div className="reference-grid">
    <div className="intro-panel">
    <section className="hero" id="home"><img className="hero-image" src={aircraft} alt="Commercial aircraft flying over the Chennai coastline" width="1600" height="900" /><div className="container hero-content"><span className="hero-eyebrow">An Indian aviation data project</span><h1>AIRIX</h1><h2>Automated Indian Airfare Index</h2><p>A real-time statistical framework for observing how domestic airfares change across routes, airlines and booking horizons.</p><div className="hero-actions"><Button asChild variant="hero" size="hero"><a href="#understand">Explore AIRIX</a></Button><Button asChild variant="heroOutline" size="hero"><a href="#how-it-works">How It Works</a></Button><Button asChild variant="heroOutline" size="hero"><a href="#explorer">Explore the Data</a></Button></div><div className="hero-disclaimer">PROPOSED CONCEPT · DEMONSTRATION DATA ONLY · NOT AN OFFICIAL GOVERNMENT INDEX</div></div></section>
    <section className="section alt"><div className="container"><SectionHeader number="01" title="Why does AIRIX matter?" description="A transparent proposal for turning comparable airfare observations into a clearer picture of fare movement."/><div className="pipeline">{pipeline.map(({icon:Icon,title,note}) => <div className="pipeline-step" key={title}><Icon size={25} strokeWidth={1.7}/><strong>{title}</strong><small>{note}</small></div>)}</div><div className="support-row"><span className="support-chip"><TrendingUp size={17}/> Airfare Movement</span><span className="support-chip"><FileChartColumn size={17}/> CPI Augmentation</span></div></div></section>
    </div>
    <section className="section" id="understand"><div className="container"><SectionHeader number="02" title="What is AIRIX?" description="AIRIX is a proposed data-driven system that collects, cleans, normalizes and analyses domestic Indian airfare data to generate a reliable picture of airfare movement."/><img className="about-aircraft" src={aircraft} alt="Aircraft in flight" /><div className="grid-4"><InfoCard icon={Database} title="Automated Data Collection">A proposed workflow for collecting permitted fare observations consistently.</InfoCard><InfoCard icon={CalendarDays} title="Multiple Booking Horizons">Compare fares at consistent intervals before departure.</InfoCard><InfoCard icon={RouteIcon} title="Route & Carrier Level Analysis">Inspect patterns across routes and airlines in comparable samples.</InfoCard><InfoCard icon={ChartNoAxesCombined} title="Supports CPI Augmentation">Potential research input to complement established measurement.</InfoCard></div><div className="notice"><strong>Project status:</strong> AIRIX is a proposed solution under SIH 2026 to support and augment the measurement of airfare for CPI analysis. It is not the official government index.</div></div></section>
    <section className="section alt" id="how-it-works"><div className="container"><SectionHeader number="03" title="How AIRIX works" description="Six stages take potential fare observations from collection to a usable analytical view."/><div className="process">{steps.map(({icon:Icon,title},i) => <div className="process-item" key={title}><b>{String(i+1).padStart(2,'0')}</b><Icon size={21} strokeWidth={1.7}/><strong>{title}</strong></div>)}</div><div className="grid-3"><div className="panel"><h3>Sources</h3><Flow items={['Airline websites','OTA platforms','Other permitted airfare sources']}/></div><div className="panel"><h3>Data pipeline</h3><Flow items={['Scraping / collection','Processing','Database','Index engine']}/></div><div className="panel"><h3>Output</h3><Flow items={['Dashboard','API']}/></div></div></div></section>
    <section className="section" id="cpi"><div className="container"><SectionHeader number="04" title="CPI → Airfare" description="A conceptual view of how airfare can be considered within the broader consumer price measurement ecosystem."/><div className="grid-2"><div className="panel"><h3>From spending to an index</h3><Flow items={['Consumer Expenditure','Goods + Services','Price Collection','Price Changes','CPI']}/></div><div className="panel"><h3>Where airfare may fit</h3><Flow items={['CPI','Transport & Communication','Airfare','AIRIX · proposed analytical support']}/></div></div><div className="notice"><strong>Current CPI update:</strong> Refer to MoSPI / NSO releases for the latest official CPI publications. This diagram is explanatory only; it does not represent an official AIRIX integration.</div></div></section>
    <section className="section alt" id="glossary"><div className="container"><SectionHeader number="05" title="Technical glossary" description="Plain-language explanations of the methods and aviation terms behind the proposal."/><GlossaryTool /></div></section>
    <section className="section" id="ecosystem"><div className="container"><SectionHeader number="06" title="Government & institutions" description="Institutional context, shown separately from AIRIX’s proposed role. No endorsement is implied."/><div className="panel"><div className="flow-node max-w-sm mx-auto !bg-primary !text-primary-foreground">Government of India · institutional context</div><div className="grid-3 mt-5"><InfoCard icon={Building2} title="MoSPI / NSO">Documented role: official statistics and CPI publications.</InfoCard><InfoCard icon={Plane} title="Ministry of Civil Aviation">Documented role: civil aviation policy and sector oversight.</InfoCard><InfoCard icon={Landmark} title="RBI">Documented role: monetary policy and inflation analysis.</InfoCard></div></div><div className="notice"><strong>Proposed AIRIX role:</strong> a possible independent analytical framework for observing airfare patterns. This concept is not sponsored, approved or endorsed by any institution shown here.</div></div></section>
    <section className="section alt" id="leadership"><div className="container"><SectionHeader number="07" title="Key people & institutional leadership" description="Illustrative profile slots to show how verified institutional leadership could be presented."/><div className="grid-4">{['Official statistics representative','Civil aviation representative','Monetary policy representative','AIRIX project representative'].map((role,i) => <div className="profile-card" key={role}><div className="profile-avatar"><UserRound size={28}/></div><h3>Profile {String(i+1).padStart(2,'0')}</h3><p>{role}<br/>Illustrative placeholder</p><Button asChild variant="outline" size="sm"><a href="#sources">View Source</a></Button></div>)}</div><div className="notice">Names, designations and details are illustrative and should be verified against respective official sources.</div></div></section>
    <section className="section" id="methodology"><div className="container"><SectionHeader number="08" title="CPI → Airfare → AIRIX" description="The proposed workflow complements, rather than replaces, established statistical processes."/><div className="grid-2"><div className="panel"><h3>Traditional / Existing Approach</h3><div className="timeline">{['Identify relevant routes','Collect airfare observations','Compile price information','Calculate price movement','CPI'].map(s => <div key={s}>{s}</div>)}</div></div><div className="panel"><h3>Why AIRIX?</h3><div className="check-list">{['Automated collection','Higher-frequency observations','Multiple booking horizons','Standardized data','Automated analysis'].map(s => <span key={s}><CircleCheck size={18}/>{s}</span>)}</div></div></div><div className="notice">AIRIX augments the existing CPI methodology and does not replace the official CPI system.</div></div></section>
    <section className="section alt" id="example"><div className="container"><SectionHeader number="09" title="A route, five booking horizons" description="Chennai → Delhi demonstrates how a sample fare series may change as departure approaches. All numbers below are illustrative data."/><ExampleTool /></div></section>
    <section className="section" id="explorer"><div className="container"><SectionHeader number="10" title="AIRIX Data Explorer" description="Explore locally generated sample fares across routes, carriers, booking horizons and dates."/><ExplorerTool /></div></section>
    <section className="section alt" id="sources"><div className="container"><SectionHeader number="11" title="Key data sources" description="Potential sources and reference material for a future, permission-aware research workflow."/><div className="grid-4">{sources.map(s => <div className="source-card" key={s.name}><span className="icon-tile"><Globe2 size={20}/></span><h3>{s.name}</h3><span className="badge">{s.category}</span><p className="mt-3">{s.detail}</p><p className="limitation"><strong>Consideration:</strong> {s.limitation}</p><SourceLink url={s.url}/></div>)}</div><div className="notice">No live collection or scraping occurs on this site. Any future use must verify source availability, permissions and terms of service.</div></div></section>
    <section className="section" id="limitations"><div className="container"><SectionHeader number="12" title="Limitations" description="A useful airfare index depends on comparing like-for-like observations and documenting what cannot be controlled."/><div className="grid-3"><InfoCard icon={TrendingUp} title="Dynamic Pricing">Displayed prices can move between searches and devices.</InfoCard><InfoCard icon={AlertCircle} title="Availability Changes">Inventory changes affect what a search returns.</InfoCard><InfoCard icon={ShieldCheck} title="Booking Restrictions">Refundability, baggage and fare conditions can vary.</InfoCard><InfoCard icon={SlidersHorizontal} title="Fare Comparability">Taxes, channels and departure windows need consistent treatment.</InfoCard><InfoCard icon={Database} title="Historical Data">Comparable archives may be incomplete or unavailable.</InfoCard></div><div className="notice">Airfare is dynamic and observed prices can vary by time, channel, availability, route and booking conditions.</div></div></section>
    <section className="section alt" id="backtesting"><div className="container"><SectionHeader number="13" title="Backtesting" description="An illustrative comparison workspace for evaluating a proposed series against a reference series."/><BacktestingTool /></div></section>
    <section className="section" id="calculator"><div className="container"><SectionHeader number="14" title="Index calculator" description="Calculate a single fare price relative with your own inputs. Results update instantly."/><IndexCalculator /></div></section>
    <section className="section alt" id="jevons"><div className="container"><SectionHeader number="15" title="Jevons Index calculator" description="Combine multiple matched fare observations with a geometric mean. Add or remove rows to explore the method."/><JevonsCalculator /></div></section>
    <section className="section" id="visual-learning"><div className="container"><SectionHeader number="16" title="Visual learning" description="A compact view of the proposed collection architecture, route network and index calculation."/><div className="grid-3"><div className="panel"><h3>Observation workflow</h3><Flow items={['Web Scraping · where permitted','Data Cleaning','Validation','Index']}/></div><div className="panel"><h3>Data architecture</h3><Flow items={['Sources','Collection','Processing','Database','Index Engine','API / Dashboard']}/></div><div className="panel"><h3>Example route network</h3><div className="flow-node">Chennai</div><div className="support-row justify-center"><span className="support-chip">↗ Delhi</span><span className="support-chip">→ Mumbai</span></div><div className="flow-node mt-4">Bengaluru → Hyderabad</div><p className="small-copy">Fictional route illustration · No network coverage claim.</p><h3>From fares to an index</h3><p className="formula">Matched fares → Price relatives → Geometric mean → Proposed index</p></div></div></div></section>
    <section className="section alt" id="about"><div className="container"><SectionHeader number="17" title="About AIRIX / SIH 2026" description="AIRIX is a project concept exploring how automated, documented data could improve understanding of Indian domestic airfare patterns."/><div className="grid-3"><InfoCard icon={BookOpen} title="SIH 2026">Proposed project context; verify competition information against official sources.</InfoCard><InfoCard icon={CircleHelp} title="Problem Statement">Exploring ways to support airfare measurement through transparent methods.</InfoCard><InfoCard icon={FileChartColumn} title="PS26506 – MoSPI">Project brief reference provided for this concept; affiliation and details require official verification.</InfoCard></div><div className="notice"><strong>Our Vision:</strong> Build a data-driven, automated system for monitoring airfare patterns in India. This site is a demonstration, not an official government publication.</div><div className="support-row"><Button asChild variant="outline"><a href="#sources">View Sources</a></Button><Button asChild variant="outline"><a href="#leadership">Team</a></Button></div></div></section>
    </div>
    <div className="reference-extras">
    <section className="section" id="sitemap"><div className="container"><SectionHeader number="18" title="Sitemap"/><div className="support-row">{[['Overview','home'],['Understand','understand'],['Explorer','explorer'],['Glossary','glossary'],['Calculators','calculator'],['Sources','sources'],['About','about']].map(([label,id]) => <a className="support-chip" href={`#${id}`} key={id}>{label}</a>)}</div></div></section>
    <section className="section alt" id="contact"><div className="container"><SectionHeader number="19" title="Contact"/><p className="small-copy">Project contact details have not been supplied. Check back for verified team contact information.</p></div></section>
    <section className="section" id="privacy"><div className="container"><SectionHeader number="20" title="Privacy"/><p className="small-copy">This demonstration uses local sample data. The filters and calculators run in your browser; entered fare values are not sent to a server or stored by this website.</p></div></section>
    </div>
  </main><Footer />
</>; }
